name: TableCloth Build Pipeline

on:
  push:
    branches-ignore: [ dev, feature/adopt-wixsharp ]

jobs:
  build:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-2022

    env:
      Solution_Name: TableCloth.sln
      Hostess_Project_Path: src\Hostess\Hostess.csproj
      TableCloth_Project_Directory: src\TableCloth
      TableCloth_Project_Path: src\TableCloth\TableCloth.csproj
      Setup_Project_Name: TableCloth.SetupBuilder
      Setup_Project_Directory: src\TableCloth.SetupBuilder
      Setup_Project_Path: src\TableCloth.SetupBuilder\TableCloth.SetupBuilder.csproj
      Platform: x64
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Setup NuGet CLI
    - name: Setup NuGet CLI
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    # Restore .NET Framework nuget packages
    - name: Restore the application (.NET Framework Part)
      run: nuget restore $env:Solution_Name

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application (.NET Core Part)
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration /m

    # Build Hostess project separately
    - name: Build Hostess project
      run: msbuild $env:Hostess_Project_Path /p:Configuration=$env:Configuration /p:Platform=$env:Platform /m

    # Build TableCloth project
    - name: Build TableCloth project
      run: dotnet build $env:TableCloth_Project_Path -r win-${{ env.Platform }} -c:$env:Configuration

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test -c:$env:Configuration
