name: Submit TableClothProject package to Windows Package Manager Community Repository

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-2022
    steps:
      - name: Submit TableCloth WinGet Package Submission
        run: |
          $packageId = "TableClothProject.TableCloth"
          $gitToken = "${{ secrets.TABLECLOTH_GITHUB_PAT }}"

          # Fetching latest release from GitHub
          $github = Invoke-RestMethod -uri "https://api.github.com/repos/yourtablecloth/TableCloth/releases"
          $targetRelease = $github | Where-Object -Property name -match 'v[\d\.]+' | Select-Object -First 1
          $installerUrl = $targetRelease | Select-Object -ExpandProperty assets -First 1 | Where-Object -Property name -match '\.exe' | Select-Object -ExpandProperty browser_download_url
          $packageVersion = $targetRelease.tag_name.Trim("v")

          # Update package using wingetcreate
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update $packageId --version $packageVersion --urls "$installerUrl|x64" --submit --token $gitToken
